### ISSUE TITLE
Open white page issue.

### ISSUE THREAD

**Issue by FullStack1106** [Flutterwave/Flutter#36]
Hello, team.
I have gotten white screen issue when I use this module in my app.
Here is log details when I call functions:

`D/EGL_emulation( 4852): app_time_stats: avg=150.40ms min=3.14ms max=2736.53ms count=19
I/flutter ( 4852): running timer => true
I/flutter ( 4852): 2022-11-12 15:26:45.217339 2022-11-12 15:09:00.329484 false
I/flutter ( 4852): URL: http://admin.upaychat.com/api/pendingrequest
I/flutter ( 4852): Body: null
I/flutter ( 4852): URL: http://admin.upaychat.com/api/wallet
I/flutter ( 4852): Body: null
D/EGL_emulation( 4852): app_time_stats: avg=18.83ms min=11.80ms max=87.80ms count=53
E/flutter ( 4852): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: PlatformException(channel-error, Unable to establish connection on channel., null, null)
E/flutter ( 4852): #0      WebViewHostApi.create (package:webview_flutter_android/src/android_webview.pigeon.dart:289:7)
E/flutter ( 4852): <asynchronous suspension>
E/flutter ( 4852): 
E/flutter ( 4852): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: PlatformException(channel-error, Unable to establish connection on channel., null, null)
E/flutter ( 4852): #0      WebSettingsHostApi.create (package:webview_flutter_android/src/android_webview.pigeon.dart:1013:7)
E/flutter ( 4852): <asynchronous suspension>
E/flutter ( 4852): 
E/flutter ( 4852): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: PlatformException(channel-error, Unable to establish connection on channel., null, null)
E/flutter ( 4852): #0      WebSettingsHostApi.setDomStorageEnabled (package:webview_flutter_android/src/android_webview.pigeon.dart:1061:7)
E/flutter ( 4852): <asynchronous suspension>
E/flutter ( 4852): 
E/flutter ( 4852): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: PlatformException(channel-error, Unable to establish connection on channel., null, null)
E/flutter ( 4852): #0      WebSettingsHostApi.setJavaScriptCanOpenWindowsAutomatically (package:webview_flutter_android/src/android_webview.pigeon.dart:1087:7)
E/flutter ( 4852): <asynchronous suspension>
E/flutter ( 4852): 
E/flutter ( 4852): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: PlatformException(channel-error, Unable to establish connection on channel., null, null)
E/flutter ( 4852): #0      WebSettingsHostApi.setSupportMultipleWindows (package:webview_flutter_android/src/android_webview.pigeon.dart:1113:7)
E/flutter ( 4852): <asynchronous suspension>
E/flutter ( 4852): 
E/flutter ( 4852): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: PlatformException(channel-error, Unable to establish connection on channel., null, null)
E/flutter ( 4852): #0      WebSettingsHostApi.setLoadWithOverviewMode (package:webview_flutter_android/src/android_webview.pigeon.dart:1239:7)
E/flutter ( 4852): <asynchronous suspension>
E/flutter ( 4852): 
E/flutter ( 4852): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: PlatformException(channel-error, Unable to establish connection on channel., null, null)
E/flutter ( 4852): #0      WebSettingsHostApi.setUseWideViewPort (package:webview_flutter_android/src/android_webview.pigeon.dart:1263:7)
E/flutter ( 4852): <asynchronous suspension>
E/flutter ( 4852): 
E/flutter ( 4852): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: PlatformException(channel-error, Unable to establish connection on channel., null, null)
E/flutter ( 4852): #0      WebSettingsHostApi.setDisplayZoomControls (package:webview_flutter_android/src/android_webview.pigeon.dart:1288:7)
E/flutter ( 4852): <asynchronous suspension>
E/flutter ( 4852): 
E/flutter ( 4852): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: PlatformException(channel-error, Unable to establish connection on channel., null, null)
E/flutter ( 4852): #0      WebSettingsHostApi.setBuiltInZoomControls (package:webview_flutter_android/src/android_webview.pigeon.dart:1313:7)
E/flutter ( 4852): <asynchronous suspension>
E/flutter ( 4852): 
E/flutter ( 4852): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: PlatformException(channel-error, Unable to establish connection on channel., null, null)
E/flutter ( 4852): #0      WebViewClientHostApi.create (package:webview_flutter_android/src/android_webview.pigeon.dart:1476:7)
E/flutter ( 4852): <asynchronous suspension>
E/flutter ( 4852): 
E/flutter ( 4852): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: PlatformException(channel-error, Unable to establish connection on channel., null, null)
E/flutter ( 4852): #0      WebSettingsHostApi.setUserAgentString (package:webview_flutter_android/src/android_webview.pigeon.dart:1163:7)
E/flutter ( 4852): <asynchronous suspension>
E/flutter ( 4852): #1      Future.wait.<anonymous closure> (dart:async/future.dart:522:21)
E/flutter ( 4852): <asynchronous suspension>
E/flutter ( 4852): #2      WebViewAndroidPlatformController.updateSettings (package:webview_flutter_android/webview_android_widget.dart:275:5)
E/flutter ( 4852): <asynchronous suspension>
E/flutter ( 4852): 
E/flutter ( 4852): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: PlatformException(channel-error, Unable to establish connection on channel., null, null)
E/flutter ( 4852): #0      WebSettingsHostApi.setMediaPlaybackRequiresUserGesture (package:webview_flutter_android/src/android_webview.pigeon.dart:1189:7)
E/flutter ( 4852): <asynchronous suspension>
E/flutter ( 4852): 
E/flutter ( 4852): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: PlatformException(channel-error, Unable to establish connection on channel., null, null)
E/flutter ( 4852): #0      DownloadListenerHostApi.create (package:webview_flutter_android/src/android_webview.pigeon.dart:1749:7)
E/flutter ( 4852): <asynchronous suspension>
E/flutter ( 4852): #1      Future.wait.<anonymous closure> (dart:async/future.dart:522:21)
E/flutter ( 4852): <asynchronous suspension>
E/flutter ( 4852): #2      WebView.setDownloadListener (package:webview_flutter_android/src/android_webview.dart:379:5)
E/flutter ( 4852): <asynchronous suspension>
E/flutter ( 4852): 
E/flutter ( 4852): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: PlatformException(channel-error, Unable to establish connection on channel., null, null)
E/flutter ( 4852): #0      WebChromeClientHostApi.create (package:webview_flutter_android/src/android_webview.pigeon.dart:1861:7)
E/flutter ( 4852): <asynchronous suspension>
E/flutter ( 4852): #1      Future.wait.<anonymous closure> (dart:async/future.dart:522:21)
E/flutter ( 4852): <asynchronous suspension>
E/flutter ( 4852): #2      WebView.setWebChromeClient (package:webview_flutter_android/src/android_webview.dart:399:5)
E/flutter ( 4852): <asynchronous suspension>
E/flutter ( 4852): 
E/flutter ( 4852): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: PlatformException(channel-error, Unable to establish connection on channel., null, null)
E/flutter ( 4852): #0      WebViewHostApi.loadUrl (package:webview_flutter_android/src/android_webview.pigeon.dart:401:7)
E/flutter ( 4852): <asynchronous suspension>
E/flutter ( 4852): 
E/flutter ( 4852): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: PlatformException(error, java.lang.IllegalStateException: Trying to create a platform view of unregistered type: plugins.flutter.io/webview
E/flutter ( 4852): 	at io.flutter.plugin.platform.PlatformViewsController$1.createForTextureLayer(PlatformViewsController.java:219)
E/flutter ( 4852): 	at io.flutter.embedding.engine.systemchannels.PlatformViewsChannel$1.create(PlatformViewsChannel.java:122)
E/flutter ( 4852): 	at io.flutter.embedding.engine.systemchannels.PlatformViewsChannel$1.onMethodCall(PlatformViewsChannel.java:60)
E/flutter ( 4852): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:262)
E/flutter ( 4852): 	at io.flutter.embedding.engine.dart.DartMessenger.invokeHandler(DartMessenger.java:295)
E/flutter ( 4852): 	at io.flutter.embedding.engine.dart.DartMessenger.lambda$dispatchMessageToQueue$0$io-flutter-embedding-engine-dart-DartMessenger(DartMessenger.java:319)
E/flutter ( 4852): 	at io.flutter.embedding.engine.dart.DartMessenger$$ExternalSyntheticLambda0.run(Unknown Source:12)
E/flutter ( 4852): 	at android.os.Handler.handleCallback(Handler.java:942)
E/flutter ( 4852): 	at android.os.Handler.dispatchMessage(Handler.java:99)
E/flutter ( 4852): 	at android.os.Looper.loopOnce(Looper.java:201)
E/flutter ( 4852): 	at android.os.Looper.loop(Looper.java:288)
E/flutter ( 4852): 	at android.app.ActivityThread.main(ActivityThread.java:7898)
E/flutter ( 4852): 	at java.lang.reflect.Method.invoke(Native Method)
E/flutter ( 4852): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
E/flutter ( 4852): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)
E/flutter ( 4852): , null, null)
E/flutter ( 4852): #0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:653:7)
E/flutter ( 4852): #1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:296:18)
E/flutter ( 4852): <asynchronous suspension>
E/flutter ( 4852): #2      TextureAndroidViewController._sendCreateMessage (package:flutter/src/services/platform_views.dart:1146:18)
E/flutter ( 4852): <asynchronous suspension>
E/flutter ( 4852): #3      AndroidViewController.create (package:flutter/src/services/platform_views.dart:792:5)
E/flutter ( 4852): <asynchronous suspension>
E/flutter ( 4852): 
`
Thank you.

**Comment by FredDominant** [comment]
Please list the steps to reproduce. It will also be helpful to state the version of the library’s.

**Comment by FullStack1106** [comment]
version of library:
flutterwave_standard: ^1.0.5

if (mode == 'flutterwave'){
  print(Uuid().v1());
  Flutterwave flutterwave = Flutterwave(
      context: context,
      publicKey: StringMessage.flutterwavePubKey,
      currency: "NGN",
      redirectUrl: "/",
      txRef: 'Upaychat${Uuid().v1()}',
      amount: totalAmount.toString(),
      customer: Customer(
          name:
'${PreferencesManager.getString(StringMessage.firstname)}
${PreferencesManager.getString(StringMessage.lastname)}',
          phoneNumber: PreferencesManager.getString(StringMessage.mobile),
          email: PreferencesManager.getString(StringMessage.email)
      ),
      paymentOptions: "ussd, card, barter, payattitude",
      customization: Customization(title: "Upaychat Deposit"),
      isTestMode: false );
  ChargeResponse response = await flutterwave.charge();
  print(response);
  Navigator.pop(context);
}

**Comment by FullStack1106** [comment]
version of library:
flutterwave_standard: ^1.0.5

if (mode == 'flutterwave'){
  print(Uuid().v1());
  Flutterwave flutterwave = Flutterwave(
      context: context,
      publicKey: StringMessage.flutterwavePubKey,
      currency: "NGN",
      redirectUrl: "/",
      txRef: 'Upaychat${Uuid().v1()}',
      amount: totalAmount.toString(),
      customer: Customer(
          name: '${PreferencesManager.getString(StringMessage.firstname)} ${PreferencesManager.getString(StringMessage.lastname)}',
          phoneNumber: PreferencesManager.getString(StringMessage.mobile),
          email: PreferencesManager.getString(StringMessage.email)
      ),
      paymentOptions: "ussd, card, barter, payattitude",
      customization: Customization(title: "Upaychat Deposit"),
      isTestMode: false );
  ChargeResponse response = await flutterwave.charge();
  print(response);
  Navigator.pop(context);
}

**Comment by FullStack1106** [comment]
I have changed some code, so I could get screen but there is strange issue.
![image](https://user-images.githubusercontent.com/117177084/201486477-85775fe2-7aea-43c3-9954-0fcf7151d6f1.png)
![image](https://user-images.githubusercontent.com/117177084/201486496-fa294fa6-0af3-400f-9eb9-1c2c4d124403.png)
![image](https://user-images.githubusercontent.com/117177084/201486502-c4d87b76-52b3-45c9-b270-9666da2ccc69.png)

Show screen at first.
and show loading screen
and show white screen
and show card screen again
and loading, white screen again.
repeat this steps.
here is log details.
this is some of log details.
E/FrameEvents(18541): updateAcquireFence: Did not find frame.
E/FrameEvents(18541): updateAcquireFence: Did not find frame.
E/FrameEvents(18541): updateAcquireFence: Did not find frame.
E/FrameEvents(18541): updateAcquireFence: Did not find frame.
E/FrameEvents(18541): updateAcquireFence: Did not find frame.
E/FrameEvents(18541): updateAcquireFence: Did not find frame.
D/EGL_emulation(18541): eglCreateContext: 0x79b37a725390: maj 3 min 0 rcv 3
E/FrameEvents(18541): updateAcquireFence: Did not find frame.
E/FrameEvents(18541): updateAcquireFence: Did not find frame.
E/FrameEvents(18541): updateAcquireFence: Did not find frame.
E/FrameEvents(18541): updateAcquireFence: Did not find frame.
E/FrameEvents(18541): updateAcquireFence: Did not find frame.
E/FrameEvents(18541): updateAcquireFence: Did not find frame.
I/PlatformViewsController(18541): Hosting view in view hierarchy for platform view: 38
D/EGL_emulation(18541): eglCreateContext: 0x79b37a71ecd0: maj 3 min 0 rcv 3
E/FrameEvents(18541): updateAcquireFence: Did not find frame.
W/cr_AwContents(18541): WebView.destroy() called while WebView is still attached to window.
W/Parcel  (18541): Expecting binder but got null!
E/FrameEvents(18541): updateAcquireFence: Did not find frame.
E/FrameEvents(18541): updateAcquireFence: Did not find frame.
E/FrameEvents(18541): updateAcquireFence: Did not find frame.
I/PlatformViewsController(18541): Hosting view in view hierarchy for platform view: 39
E/FrameEvents(18541): updateAcquireFence: Did not find frame.
W/Parcel  (18541): Expecting binder but got null!
D/EGL_emulation(18541): eglCreateContext: 0x79b37a724e50: maj 3 min 0 rcv 3
W/cr_AwContents(18541): WebView.destroy() called while WebView is still attached to window.
E/FrameEvents(18541): updateAcquireFence: Did not find frame.
E/FrameEvents(18541): updateAcquireFence: Did not find frame.
E/FrameEvents(18541): updateAcquireFence: Did not find frame.
W/chromium(18541): [WARNING:spdy_session.cc(3541)] Received HEADERS for invalid stream 31
E/FrameEvents(18541): updateAcquireFence: Did not find frame.
D/EGL_emulation(18541): app_time_stats: avg=52.00ms min=3.77ms max=784.89ms count=29
D/EGL_emulation(18541): app_time_stats: avg=91.50ms min=13.19ms max=782.14ms count=18
E/FrameEvents(18541): updateAcquireFence: Did not find frame.
D/EGL_emulation(18541): app_time_stats: avg=206.45ms min=7.93ms max=794.44ms count=5
E/FrameEvents(18541): updateAcquireFence: Did not find frame.
E/FrameEvents(18541): updateAcquireFence: Did not find frame.
E/FrameEvents(18541): updateAcquireFence: Did not find frame.
E/FrameEvents(18541): updateAcquireFence: Did not find frame.
E/FrameEvents(18541): updateAcquireFence: Did not find frame.
E/FrameEvents(18541): updateAcquireFence: Did not find frame.
E/FrameEvents(18541): updateAcquireFence: Did not find frame.
E/FrameEvents(18541): updateAcquireFence: Did not find frame.
E/FrameEvents(18541): updateAcquireFence: Did not find frame.
E/FrameEvents(18541): updateAcquireFence: Did not find frame.
E/FrameEvents(18541): updateAcquireFence: Did not find frame.
E/FrameEvents(18541): updateAcquireFence: Did not find frame.
E/FrameEvents(18541): updateAcquireFence: Did not find frame.
E/FrameEvents(18541): updateAcquireFence: Did not find frame.
E/FrameEvents(18541): updateAcquireFence: Did not find frame.
E/FrameEvents(18541): updateAcquireFence: Did not find frame.
D/EGL_emulation(18541): app_time_stats: avg=58.87ms min=7.88ms max=570.11ms count=17
D/EGL_emulation(18541): app_time_stats: avg=77.41ms min=13.94ms max=586.58ms count=13
E/FrameEvents(18541): updateAcquireFence: Did not find frame.
E/FrameEvents(18541): updateAcquireFence: Did not find frame.
E/FrameEvents(18541): updateAcquireFence: Did not find frame.
E/FrameEvents(18541): updateAcquireFence: Did not find frame.
E/FrameEvents(18541): updateAcquireFence: Did not find frame.
E/FrameEvents(18541): updateAcquireFence: Did not find frame.
E/FrameEvents(18541): updateAcquireFence: Did not find frame.
E/FrameEvents(18541): updateAcquireFence: Did not find frame.
D/EGL_emulation(18541): app_time_stats: avg=41.63ms min=8.52ms max=571.35ms count=24
E/FrameEvents(18541): updateAcquireFence: Did not find frame.
E/FrameEvents(18541): updateAcquireFence: Did not find frame.
E/FrameEvents(18541): updateAcquireFence: Did not find frame.
E/FrameEvents(18541): updateAcquireFence: Did not find frame.
E/FrameEvents(18541): updateAcquireFence: Did not find frame.
E/FrameEvents(18541): updateAcquireFence: Did not find frame.
E/FrameEvents(18541): updateAcquireFence: Did not find frame.
E/FrameEvents(18541): updateAcquireFence: Did not find frame.
E/FrameEvents(18541): updateAcquireFence: Did not find frame.
E/FrameEvents(18541): updateAcquireFence: Did not find frame.
E/FrameEvents(18541): updateAcquireFence: Did not find frame.
E/FrameEvents(18541): updateAcquireFence: Did not find frame.
E/FrameEvents(18541): updateAcquireFence: Did not find frame.
E/FrameEvents(18541): updateAcquireFence: Did not find frame.
E/FrameEvents(18541): updateAcquireFence: Did not find frame.
E/FrameEvents(18541): updateAcquireFence: Did not find frame.
E/FrameEvents(18541): updateAcquireFence: Did not find frame.
E/FrameEvents(18541): updateAcquireFence: Did not find frame.
E/FrameEvents(18541): updateAcquireFence: Did not find frame.
E/FrameEvents(18541): updateAcquireFence: Did not find frame.
E/FrameEvents(18541): updateAcquireFence: Did not find frame.
E/FrameEvents(18541): updateAcquireFence: Did not find frame.
E/FrameEvents(18541): updateAcquireFence: Did not find frame.
E/FrameEvents(18541): updateAcquireFence: Did not find frame.
E/FrameEvents(18541): updateAcquireFence: Did not find frame.
E/FrameEvents(18541): updateAcquireFence: Did not find frame.
E/FrameEvents(18541): updateAcquireFence: Did not find frame.
E/FrameEvents(18541): updateAcquireFence: Did not find frame.
..............
..............
Thank you.

**Comment by irfan512** [comment]
Same Issue I am Face Right Now

**Comment by FredDominant** [comment]
Hello @paulpascal, @irfan512, could you please share short videos/gifs of this, and also screenshots of how you initiate the library
